// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-merge'
  | 'menuitem-prefer'
  | 'menuitem-update'
  | 'menuitem-update-pdf'
  | 'merge-confirm'
  | 'pref-behavior'
  | 'pref-downloadJournalPDF'
  | 'pref-enable'
  | 'pref-enable-arXivMerge'
  | 'pref-enable-arXivUpdate'
  | 'pref-enable-preferPDF'
  | 'pref-enable-updatePDF'
  | 'pref-help'
  | 'pref-merge-arXiv-warn'
  | 'pref-merge-arXivExtra'
  | 'pref-merge-arXivURL'
  | 'pref-merge-preferJournalPDF'
  | 'pref-merge-trashUnannotatedPDF'
  | 'pref-source'
  | 'pref-source-arXiv'
  | 'pref-source-dblp'
  | 'pref-source-doi'
  | 'pref-source-pubmed'
  | 'pref-source-semanticScholar'
  | 'prefs-title'
  | 'update-pdf-prompt'
  | 'update-prompt';
