// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "downloadJournalPDF": boolean;
      "features.arXivMerge": boolean;
      "features.arXivUpdate": boolean;
      "features.preferPDF": boolean;
      "features.updatePDF": boolean;
      "updateSource.doi": boolean;
      "updateSource.semanticScholar": boolean;
      "updateSource.dblp": boolean;
      "updateSource.pubmed": boolean;
      "updateSource.arXiv": boolean;
      "mergePreferJournalPDF": boolean;
      "merge.arXivExtra": boolean;
      "merge.arXivURL": boolean;
      "merge.trashUnannotatedPDF": boolean;
    };
  }
}
