name: Build or Release

on:
  push:
    branches:
      - main
    tags:
      - v**

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: ${{ startsWith(github.ref, 'refs/heads/') && 'Build' || 'Release' }}
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/') ||
      github.event.head_commit.message != 'chore(publish)*'
    env:
      GITHUB_TOKEN: ${{ secrets.GitHub_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install -f

      - name: Build
        run: npm run build

      - name: Create artifact
        if: startsWith(github.ref, 'refs/heads/')
        uses: actions/upload-artifact@v4
        with:
          name: arXiv-workflow-for-zotero
          path: build/zotero-arxiv-workflow.xpi

      - name: Lint code
        if: startsWith(github.ref, 'refs/heads/')
        run: npm run lint

      - name: Release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          npm run release
          sleep 1s

      - name: Notify release
        if: startsWith(github.ref, 'refs/tags/')
        uses: apexskier/github-release-commenter@v1
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            :rocket: _This ticket has been resolved in {release_tag}. See {release_link} for release notes._
